### ISSUE TITLE
Cifsd kernel server keeps serving files, even if the cifsd userspace service stopped.

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd-tools#65]
I just encountered the case were the cifsd userspace service did end, was killed, yet the share was still accessible. I would like to ensure that if we end, kill the userspace service that the shares become inaccessible and we can remove the kernel module. So some option for the userspace tools to force the kernel module to end and allow removal.

Atm after this happens i cant remove the module anymore:
```
rmmod cifsd
unloading the module failed
```

**Comment by Andy2244** [comment]
It seems after accessing a share once, even after closing the smb session on the client the connections are kept open.
```
net use * /delete
There are no entries in the list.

PS C:\WINDOWS\system32> Get-SmbConnection

ServerName ShareName UserName    Credential  Dialect NumOpens
---------- --------- --------    ----------  ------- --------
router     share     GAMEPC\andy GAMEPC\andy 3.1.1   1
```

**Comment by sergey-senozhatsky** [comment]
This is by design.
If user-space does not respond then you won't be able to setup new sessions, tree
connections or have new user logins. But sessions and tree connects which were
already verified/established will remain valid/available. We need user space only when
we do loging and tree connect; after that session does not depend on user-space
service.

You can set "ipc timeout" [global]  (in seconds) to enable server->user-space heartbeat
requests; so kcifsd can monitor user-space and reset itself if user-space cifsd dies.

-ss

**Comment by sergey-senozhatsky** [comment]
> There also seems to-be a related problem, that changed user configurations are not honored?

Yet to be done. We also don't handle lanman RPC which is used for remote adminstration.

> I than changed the access and afterwards re-started cifsd -n.
> guest ok = no
> valid users = andy

Established sessions remain valid. We don't "re-do" login/tree connect/etc sequences for
already existing sessions. We probably can forcibly kill all sessions and expect all clients
to re-connect, re-open files. etc. etc.

-ss

**Comment by Andy2244** [comment]
ok thanks for the explanation, will play around with `ipc timeout`.

The problem is that i cant write a init script that ensures the service is closed/disabled, if the user request a service stop, because i cant find a way to forcefully end/remove a kernel module. That's not a huge problem, but if there is a reasonable way to add a option that allows closeing all connections and remove the module, this would be more in line with how other services we use behave. As example samba3/4 can be directly stopped/killed and operation stops.

**Comment by sergey-senozhatsky** [comment]
ipc timeout should deal with the "close connections" part, but I'm afraid we can't unload the
module from unprivileged user-space cifsd; nor can we ask the module to somehow unload
itself. From that prospective cifsd is more like nfsd.

---

The basic idea was to run user-space cifsd as a stateless "policy engine" or some sort of a
database on steroids; which can lookup user pwd by name, lookup share config by name,
handle MAP_TO_GUEST/etc policy, handle DCE RPC, and so on. We are not quite there
yet - need to move user logon handling completely to user-space, so we can have things
like LDAP or 3rd party -based login. Otherwise kcifsd does not need user-space cifsd.

-ss

**Comment by Andy2244** [comment]
Ok what about some /proc/sys option for the module? So i could directly communicate with the kernel module and do something like `echo false > /proc/sys/cifsd/enable-service` ?

**Comment by sergey-senozhatsky** [comment]
What do you mean by "enable service"? The module needs to be loaded in order to handle sysfs
ops. kcifsd does not listen on TCP port when you just insmod it. We configure kcifsd when we
start user-space cifsd (it sends relevant [global] config data over netlink). Only after this kcifsd is
ready to process TCP connections. Should user-space cifsd crash/stop, kcifsd will not be able to
create new sessions, open new tree connections, or logon new users; but still will listen on
TCP connections and handle SMB commands for already existing sessions (as much as it can;
it obvisouly cannot handle SRVSVC or any other DCE RPC, because it needs user-space cifsd
for that).

With "ipc timeout" enabled, after some time, kcifsd will stop listening on TCP ports and destroy
existing sessions. Basically it will reset (or disable) itself. Does this work for you?

I'm a bit reluctant when it comes to adding a sysfs knob which would enable for unprivileged
reset of kcifsd; that's a huge hammer. Does nfsd permit unprivileged reset?

-ss

**Comment by Andy2244** [comment]
> With "ipc timeout" enabled, after some time, kcifsd will stop listening on TCP ports and destroy
> existing sessions. Basically it will reset (or disable) itself. Does this work for you?

Mhh so setting `ipc timeout` to 3 seconds, should close all sessions after i kill the cifsd userspace process? So after a 3 sec timeout i should be able to rmmod cifsd? Is it safe to use such a low timeout?
 
I'm just looking for a clean way to stop the service and free all its resources.

**Comment by sergey-senozhatsky** [comment]
> Mhh so setting ipc timeout to 3 seconds, should close all sessions after i kill the cifsd userspace process? 

Yes, it should (modulo bugs which we might have there :))

> So after a 3 sec timeout i should be able to rmmod cifsd?

Theoretically yes. 
You can monitor 

     cat /sys/class/cifsd-control/stats

it shows server state. "running" means that the server cannot be rmmod-ed,
"startup" means that the server is in initial state (reset) and can be rmmod-ed.

>  Is it safe to use such a low timeout?

Well, case by case. I usually set it to ~20 seconds (or more).

-ss

**Comment by Andy2244** [comment]
Just to-be clear, `ipc timeout` is not something like sambas `deadtime` or `keepalive`, so it only kicks in after cifsd userspace process was killed/ended?

**Comment by sergey-senozhatsky** [comment]
It sems that both `deadtime` and `keepalive` are per-TCP connection / per-client.
`ipc timeout` kills all connections.

-ss

**Comment by Andy2244** [comment]
@sergey-senozhatsky doesn't work for me, tried 3 and 3000 as values, since its not clear is this in seconds or ms? 
```
[global]
	server string = CIFSD on OpenWRT
	ipc timeout = 3000
	map to guest = Bad User
```

If cifsd userspace service ends, the share is still available and i also cant remove the module. I did map a network drive as share and it seems after initial login, the share is accessible forever even without any userspace service running anymore?

**Comment by sergey-senozhatsky** [comment]
> tried 3 and 3000 as values, since its not clear is this in seconds or ms?

Seconds.

> doesn't work for me

Hmm. Anything interesting in dmesg output?
"No IPC daemon response for XXXs"?

-ss

**Comment by Andy2244** [comment]
@sergey-senozhatsky ok seem the config was not updated after i switched from 3000 to 3. Did run the test again with a value of 5, but did a reboot beforehand. Now i get:
```
Sat Feb  9 11:51:37 2019 user.notice cifsd: Starting CIFS/SMB userspace service.
Sat Feb  9 11:51:42 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:51:47 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:51:47 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: treecon: net share permits guest login
Sat Feb  9 11:51:52 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:51:57 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:52:03 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:52:08 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:52:13 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:52:18 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:52:23 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:52:28 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:52:33 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: HEARTBEAT frame from the server
Sat Feb  9 11:52:34 2019 user.notice cifsd: Stopping CIFS/SMB userspace service.
Sat Feb  9 11:52:34 2019 local5.err cifsd: [cifsd-worker/13529]: ERROR: Child received signal: 15 (Terminated)
Sat Feb  9 11:52:34 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: Kill share share
Sat Feb  9 11:52:34 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: Kill share ipc$
Sat Feb  9 11:52:34 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: Kill user nobody
Sat Feb  9 11:52:34 2019 local5.debug cifsd: [cifsd-worker/13529]: DEBUG: Kill user smbuser
Sat Feb  9 11:52:34 2019 local5.debug cifsd: [cifsd-manager/13528]: DEBUG: detected pid 13529 termination
Sat Feb  9 11:52:34 2019 local5.info cifsd: [cifsd-manager/13528]: INFO: Exiting. Bye!
Sat Feb  9 11:52:38 2019 kern.err kernel: [  651.658438] kcifsd: cifsd_ipc_heartbeat:473: No IPC daemon response for 5s
Sat Feb  9 11:52:38 2019 kern.err kernel: [  651.665407] kcifsd: tcp_stop_sessions:650: Stop session handler kcifsd:6716/13533
```

So after waiting 6-7 seconds on the stop_service() trigger the module can be removed and the connections close. As you can see the only thing that should change is the HEARTBEAT log output, since it quickly floods the log.
So you see any problems setting this to 5-7 seconds by default for my package? Anything higher would mean the openwrt stop service UI would be stalled for this long after clicking the button.

**Comment by sergey-senozhatsky** [comment]
@Andy2244   OK.

Admittedly, this scheme is not entirely reliable, tho. If kcifsd TCP workers misbehave then we are done.

> the only thing that should change is the HEARTBEAT log output

Right.

> So you see any problems setting this to 5-7 seconds by default for my package?

5-7s sounds OK. User-space cifsd has a `do nothing` "manager" process and a worker process.
Manager process just spins in a `while (1) {fork(); waitpid(); }` loop and restarts worker process
when it crashes; but manager ratelimits forks, so it's `while (1) {fork(); waitpid(); sleep(1); }`. If
the system is busy, manager process can be preempted for a while, so `ipc timeout` of 2s or 1s
is just too short, we might not be able to re-start worker in time. But 5-7s sounds reasonably large. 

-ss

**Comment by Andy2244** [comment]
ok will set default to 8s for openwrt, if you maybe find, implement a more direct way to invoke a reset/close let me know.

thanks
